### ISSUE TITLE
Very minor issue with movement

### ISSUE THREAD

**Issue by frank-taylor-pcg** [kidscancode/topdown_tanks#1]
In the `control()` function of `Player.gd`: if you hold W and S down at the same time the tank will always move backwards. That could be fixed by mimicking what you did with the `rot_dir` variable:

	var movement = 0
	if Input.is_action_pressed("forward"):
		movement += 1
	if Input.is_action_pressed("back"):
		movement -= 1
	
	if movement < 0:
		movement /= 2.0
	
	velocity = Vector2(movement * speed, 0).rotated(rotation)

**Comment by cbscribe** [comment]
Good point - I was just thinking of slower backward movement. I'll fix that soon!

**Comment by cbscribe** [comment]
Fixed in current master with
```
if Input.is_action_pressed('forward'):
    velocity += Vector2(speed, 0).rotated(rotation)
if Input.is_action_pressed('back'):
    velocity += Vector2(-speed, 0).rotated(rotation)
    velocity /= 2.0
```
